FROM node:20-alpine
WORKDIR /app

# We need openssl in dev to make a self-signed cert automatically
RUN apk add --no-cache openssl

# Copy package files
COPY package.json package-lock.json

# Install deps
RUN npm ci --omit=optional

# Copy the rest (including entrypoint + future source files)
COPY . .

EXPOSE 8443
CMD ["sh", "/app/entrypoint.sh"]
